version: "3.8"
services:
  knowage:
    container_name: $APP_CONTAINER_NAME-server
    image: knowagelabs/knowage-server-docker:$APP_VERSION
    restart: always
    depends_on:
      - knowagedb
      - knowagecache
    ports:
      - "$APP_PORT:8080"
    volumes:
      - $VOLUMES_PATH_PREFIX/resources:/home/knowage/apache-tomcat/resources
    environment:
      - DB_HOST=$DB_MARIADB_HOST
      - DB_PORT=$DB_MARIADB_PORT
      - DB_DB=$DB_MARIADB_NAME
      - DB_USER=$DB_MARIADB_USER
      - DB_PASS=$DB_MARIADB_PASSWORD

      - CACHE_DB_HOST=$DB_MARIADB_CACHE_HOST
      - CACHE_DB_PORT=$DB_MARIADB_CACHE_PORT
      - CACHE_DB_DB=$DB_MARIADB_CACHE_NAME
      - CACHE_DB_USER=$DB_MARIADB_CACHE_USER
      - CACHE_DB_PASS=$DB_MARIADB_PASSWORD

      - HMAC_KEY=$APP_HMAC_KEY
      - PASSWORD_ENCRYPTION_SECRET=$APP_PASSWORD_ENCRYPTION_SECRET
      - PUBLIC_ADDRESS=localhost

  # knowage 8.0 need add this line:
  hazelcast:
    image: hazelcast/hazelcast:3.6.5
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=hazelcast -Dhazelcast.config=/opt/hazelcast/hazelcast.xml
    volumes:
      - ./src/hazelcast-server.xml:/opt/hazelcast/hazelcast.xml

  knowagepython:
    container_name: $APP_CONTAINER_NAME-python
    image: knowagelabs/knowage-python-docker:$APP_VERSION
    restart: always
    environment:
      - HMAC_KEY=$APP_HMAC_KEY
      - KNOWAGE_PUBLIC_ADDRESS=knowage
      - PUBLIC_ADDRESS=localhost

  knowager:
    container_name: $APP_CONTAINER_NAME-r
    image: knowagelabs/knowage-r-docker:$APP_VERSION
    restart: always
    environment:
      - HMAC_KEY=$APP_HMAC_KEY

  knowagedb:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $APP_CONTAINER_NAME-mariadb-server
    restart: always
    environment:
      - MYSQL_USER=$DB_MARIADB_USER
      - MYSQL_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_DATABASE=$DB_MARIADB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
    ports: 
      - "$DB_MARIADB_PORT:3306"
    volumes:
      - "$VOLUMES_PATH_PREFIX/db:/var/lib/mysql"

  knowagecache:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $APP_CONTAINER_NAME-mariadb-cache
    restart: always
    environment:
      - MYSQL_USER=$DB_MARIADB_CACHE_USER
      - MYSQL_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_DATABASE=$DB_MARIADB_CACHE_NAME
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - "$VOLUMES_PATH_PREFIX/cache:/var/lib/mysql"

networks:
  default:
      name: "$APP_NETWORK"
