# image: https://hub.docker.com/r/knowagelabs/knowage-server-docker

version: "3.8"
services:
  knowage:
    container_name: $APP_NAME
    image: knowagelabs/knowage-server-docker:$APP_VERSION
    restart: always
    depends_on:
      - knowagedb
      - knowagecache
      - hazelcast
    ports:
      - "$APP_PORT:8080"
    volumes:
      - knowage:/home/knowage/apache-tomcat/resources
    environment:
      - DB_HOST=$APP_NAME-db
      - DB_PORT=3306
      - DB_DB=$DB_MARIADB_NAME
      - DB_USER=$DB_MARIADB_USER
      - DB_PASS=$DB_MARIADB_PASSWORD

      - CACHE_DB_HOST=$APP_NAME-cache
      - CACHE_DB_PORT=3306
      - CACHE_DB_DB=$DB_MARIADB_NAME
      - CACHE_DB_USER=$DB_MARIADB_USER
      - CACHE_DB_PASS=$DB_MARIADB_PASSWORD

      - HMAC_KEY=$APP_HMAC_KEY
      - PASSWORD_ENCRYPTION_SECRET=$APP_PASSWORD_ENCRYPTION_SECRET
      - PUBLIC_ADDRESS=$APP_URL

      - HAZELCAST_HOSTS=hazelcast
      - HAZELCAST_PORT=5701

  hazelcast:
    image: hazelcast/hazelcast:3.6.5
    container_name: $APP_NAME-hazelcast
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=hazelcast -Dhazelcast.config=/opt/hazelcast/hazelcast.xml
    volumes:
      - ./src/hazelcast-server.xml:/opt/hazelcast/hazelcast.xml

  knowagepython:
    image: knowagelabs/knowage-python-docker:$APP_VERSION
    container_name: $APP_NAME-python
    restart: always
    environment:
      - HMAC_KEY=$APP_HMAC_KEY
      - KNOWAGE_PUBLIC_ADDRESS=knowage
      - PUBLIC_ADDRESS=$APP_URL

  knowager:
    image: knowagelabs/knowage-r-docker:$APP_VERSION
    container_name: $APP_NAME-r
    restart: always
    environment:
      - HMAC_KEY=$APP_HMAC_KEY

  knowagedb:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $APP_NAME-db
    restart: always
    environment:
      - MYSQL_USER=$DB_MARIADB_USER
      - MYSQL_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_DATABASE=$DB_MARIADB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
    volumes:
      - "db:/var/lib/mysql"

  knowagecache:
    image: mariadb:$DB_MARIADB_VERSION
    container_name: $APP_NAME-cache
    restart: always
    environment:
      - MYSQL_USER=$DB_MARIADB_USER
      - MYSQL_PASSWORD=$DB_MARIADB_PASSWORD
      - MYSQL_DATABASE=$DB_MARIADB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_MARIADB_PASSWORD
    volumes:
      - "cache:/var/lib/mysql"

networks:
  default:
      name: "$APP_NAME"

volumes:
  db:
  cache:
  knowage:
